package HP.FOT.WxNotam.WeatherService.MessageContracts;

import HP.FOT.WxNotam.Webreferences.*;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//C# TO JAVA CONVERTER NOTE: There is no Java equivalent to C# namespace aliases:
//using WCF = System.ServiceModel;

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [WCF: :MessageContract(IsWrapped = false)][WCF::XmlSerializerFormat] public partial class RetrieveTextWeatherResponse
public class RetrieveTextWeatherResponse
{
	private RetrieveTextWeatherRS retrieveTextWeatherRS;

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.MessageBodyMember(Namespace = "http://www.eds.com/AirlineSOASchema/TextWeather/RetrieveTextWeatherRS", Order = 0)][System.Xml.Serialization.XmlElementAttribute] public RetrieveTextWeatherRS RetrieveTextWeatherRS
	public final RetrieveTextWeatherRS getRetrieveTextWeatherRS()
	{
		return retrieveTextWeatherRS;
	}
	public final void setRetrieveTextWeatherRS(RetrieveTextWeatherRS value)
	{
		retrieveTextWeatherRS = value;
	}

	public RetrieveTextWeatherResponse()
	{
	}

	public RetrieveTextWeatherResponse(RetrieveTextWeatherRS retrieveTextWeatherRS)
	{
		this.retrieveTextWeatherRS = retrieveTextWeatherRS;
	}
}